import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between shadow p-4">

          <Image
              className="h-8 w-auto"
              src="/img/iea-logo.png"
              alt="IEA Logo"
              width={180}
              height={30}
            />


          <div className="text-right">
            Test for Web developer (Grade GA4) - ref1720T
          </div>

        </div>

        {children}
      </body>
    </html>
  );
}
